apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gidx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gidx
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-gidx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gidx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gidx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bkto-tenant/rhtap-demo-app/hacbs-test-project-gidx@sha256:042a9ee64277f1fa5c7c29dbc1bf61fc3eb93932f94fc2339506c6687a60e40d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
