apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gidx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bkto-tenant/rhtap-demo-app/hacbs-test-project-gidx@sha256:331ac6218ea109bf9f941d9591edea17d5c7c530164c4f1e34fd956e9d2cd689
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
